apiVersion: v1
kind: Service
metadata:
  name: orderer
spec:
  selector:
    app: hyperledger
    orderer-id: "{{ .Values.ordererName }}"
  type: ClusterIP
  clusterIP: 10.101.10.2
  ports:
    - name: listen-endpoint
      protocol: TCP
      port: 7050
      targetPort: 7050