apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: hyperledger
    ca-id: {{ .Values.caName }}

spec:
  containers:
    - name: {{ .Values.caName }}
      image:  hyperledger/fabric-ca:{{ .Chart.AppVersion }}      
      env: 
        - name:  FABRIC_CA_HOME
          value: /etc/hyperledger/fabric/ca
        - name:  CA_CFG_PATH
          value: /etc/hyperledger/fabric/config
        - name:  FABRIC_CA_SERVER_CA_NAME
          value: {{ .Values.FABRIC_CA_SERVER_CA_NAME }}
        - name:  FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: {{ .Values.FABRIC_CA_SERVER_CA_CERTFILE }}
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: {{ .Values.FABRIC_CA_SERVER_CA_KEYFILE }}
        - name: FABRIC_CA_SERVER_DB_DATASOURCE
          value: /etc/hyperledger/fabric/data/fabric-ca-server.db
        # - name:  FABRIC_CA_SERVER_TLS_CERTFILE
        #   value: $tlsCert
        # - name:  FABRIC_CA_SERVER_TLS_KEYFILE
        #   value: $tlsKey
      ports:
        - containerPort: 7054
      command:  ["/bin/sh"]
      args: ["-c", "fabric-ca-server start -b {{ .Values.FABRIC_CA_ADMIN}}:{{ .Values.FABRIC_CA_ADMIN_PW }}"]
      volumeMounts:
        - name: fabric
          subPath: {{ .Values.orgCaPath }}
          mountPath: /etc/hyperledger/fabric/crypto
        - name: fabric
          subPath: data/{{ .Values.caName }}
          mountPath: /etc/hyperledger/fabric/data
        - name: fabric
          subPath: config/{{ .Values.caName }}
          mountPath: /etc/hyperledger/fabric/config
  volumes:
    - name: fabric
      persistentVolumeClaim:
        claimName: fabric-pvc                    
    - name: run
      hostPath:
        path: /var/run
