---
  Organizations:
      - &PeerMSP
          Name: PeerMSP
          ID: PeerMSP
          MSPDir: ../msp
          Policies: &DevOrgPolicies
              Readers:
                  Type: Signature
                  Rule: "OR('PeerMSP.member')"
              Writers:
                  Type: Signature
                  Rule: "OR('PeerMSP.member')"
              Admins:
                  Type: Signature
                  Rule: "OR('PeerMSP.admin')"
          AnchorPeers:
              - Host: peer0
                Port: 7051
                
  Capabilities:
      Channel: &ChannelCapabilities
          V1_3: true
      Orderer: &OrdererCapabilities
          V1_1: true
      Application: &ApplicationCapabilities
          V1_3: true
          V1_2: false
          V1_1: false

  Application: &ApplicationDefaults
      ACLs: &ACLsDefault
          lscc/ChaincodeExists: /Channel/Application/Readers
          lscc/GetDeploymentSpec: /Channel/Application/Readers
          lscc/GetChaincodeData: /Channel/Application/Readers
          lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
          qscc/GetChainInfo: /Channel/Application/Readers
          qscc/GetBlockByNumber: /Channel/Application/Readers
          qscc/GetBlockByHash: /Channel/Application/Readers
          qscc/GetTransactionByID: /Channel/Application/Readers
          qscc/GetBlockByTxID: /Channel/Application/Readers
          cscc/GetConfigBlock: /Channel/Application/Readers
          cscc/GetConfigTree: /Channel/Application/Readers
          cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
          peer/Propose: /Channel/Application/Writers
          peer/ChaincodeToChaincode: /Channel/Application/Readers
          event/Block: /Channel/Application/Readers
          event/FilteredBlock: /Channel/Application/Readers
      Organizations:
      Policies: &ApplicationDefaultPolicies
          Readers:
              Type: ImplicitMeta
              Rule: "ANY Readers"
          Writers:
              Type: ImplicitMeta
              Rule: "ANY Writers"
          Admins:
              Type: ImplicitMeta
              Rule: "MAJORITY Admins"
      Capabilities:
          <<: *ApplicationCapabilities

  Orderer: &OrdererDefaults
      OrdererType: solo
      Addresses:
          - orderer:7050
      BatchTimeout: 2s
      BatchSize:
          MaxMessageCount: 10
          AbsoluteMaxBytes: 10 MB
          PreferredMaxBytes: 512 KB
      MaxChannels: 0
      Kafka:
          Brokers:
              - kafka0:9092
              - kafka1:9092
              - kafka2:9092
      Organizations:
      Policies:
          Readers:
              Type: ImplicitMeta
              Rule: "ANY Readers"
          Writers:
              Type: ImplicitMeta
              Rule: "ANY Writers"
          Admins:
              Type: ImplicitMeta
              Rule: "MAJORITY Admins"
          BlockValidation:
              Type: ImplicitMeta
              Rule: "ANY Writers"
      Capabilities:
          <<: *OrdererCapabilities

  Channel: &ChannelDefaults
      Policies:
          Readers:
              Type: ImplicitMeta
              Rule: "ANY Readers"
          Writers:
              Type: ImplicitMeta
              Rule: "ANY Writers"
          Admins:
              Type: ImplicitMeta
              Rule: "MAJORITY Admins"
      Capabilities:
          <<: *ChannelCapabilities

  Profiles:
      DevSingleMSPSolo:
          <<: *ChannelDefaults
          Orderer:
              <<: *OrdererDefaults
              Organizations:
                  - *PeerMSP
          Consortiums:
              DevConsortium:
                  Organizations:
                      - *PeerMSP
      DevSingleMSPChannel:
          Consortium: DevConsortium
          Application:
              <<: *ApplicationDefaults
              Organizations:
                  - *PeerMSP