apiVersion: v1
kind: Pod
metadata: 
  name: fabric-cli

spec:
  serviceAccountName: fabric
  containers:
    - name: fabric-cli
      image: hyperledger/fabric-tools:1.4.4
      command: 
        - "/bin/bash"
      args: 
        - "-c"
        - "while true; do sleep 10; done"
      env:
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/config
        - name: CORE_PEER_LOCALMSPID
          value: {{ .Values.MSPName }}
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/fabric/msp
        - name: CORE_PEER_ADDRESS
          value: {{ .Values.CORE_PEER_ADDRESS }} 
        - name: FABRIC_LOGGING_SPEC
          value: INFO                             
      volumeMounts:
        - name: localmsp-peeradmin
          mountPath: /etc/hyperledger/fabric/msp                
        - name: config
          mountPath: /etc/hyperledger/fabric/config
  volumes:
    - name: localmsp-peeradmin
      configMap:
        name: {{ .Release.Name }}-configmap
        items:
          - key: ca-cert.pem
            path: cacerts/ca.dev.angusy.net-cert.pem
          - key: PeerAdmin-cert.pem
            path: admincerts/Admin
          - key: PeerAdmin-cert.pem
            path: signcerts/Admin
          - key: PeerAdmin-key.pem
            path: keystore/Admin
    - name: config
      configMap:
        name: {{ .Release.Name }}-configmap
        items:
          - key: configtx.yaml
            path: configtx.yaml
          - key: core.yaml
            path: core.yaml
    