apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.peerName }}"
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
  type: ClusterIP
  clusterIP: 10.101.10.3
  ports:
    - name: external-listen-endpoint
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: chaincode-listen
      protocol: TCP
      port: 7052
      targetPort: 7052
    - name: couchdb-futon
      protocol: TCP
      port: 5984
      targetPort: 5984
