apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.caName }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
  type: ClusterIP
  clusterIP: 10.101.10.1
  ports:
    - name: endpoint
      protocol: TCP
      port: 7054
      targetPort: 7054