apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric-explorer.fullname" . }}
  labels:
    {{- include "fabric-explorer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fabric-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fabric-explorer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fabric-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: hyperledger/explorer:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_HOST
              value: localhost
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
            - name: DISCOVERY_AS_LOCALHOST
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /opt/explorer/app/platform/fabric
        - name: {{ .Chart.Name }}-db
          image: hyperledger/explorer-db:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_DATABASE
              value: fabricexplorer
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
