apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}

spec:       
  containers:
    - name: {{ .Chart.Name }}
      image:  hyperledger/fabric-tools:{{ .Chart.AppVersion }}
      env:  
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/config
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: {{ .Values.CORE_CHAINCODE_LOGGING_LEVEL }}
        - name: GOPATH
          value: /opt/gopath
        - name: FABRIC_LOGGING_SPEC
          value: {{ .Values.FABRIC_LOGGING_SPEC }}
        - name: CORE_PEER_ID
          value: {{ .Values.CORE_PEER_ID }}
        - name: CORE_PEER_ADDRESS
          value: {{ .Values.CORE_PEER_ADDRESS }}
        - name: CORE_PEER_LOCALMSPID
          value: {{ .Values.MSPName }}
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/fabric/crypto/msp
      workingDir: /etc/hyperledger/fabric
      command: [ "/bin/sh" ]
      args: ["-c", "while true; do sleep 10; done"]
      volumeMounts:
        - name: run
          mountPath: /host/var/run/
        - name: fabric
          subPath: config/cli
          mountPath: /etc/hyperledger/fabric/config
        - name: fabric
          subPath: {{ .Values.MSPPath }}
          mountPath: /etc/hyperledger/fabric/crypto
        - name: fabric
          subPath: blocks
          mountPath: /etc/hyperledger/fabric/blocks
        - name: fabric
          subPath: data/cli
          mountPath: /etc/hyperledger/fabric/chaincode
        - name: fabric
          subPath: admin
          mountPath: /etc/hyperledger/fabric/admin
  volumes:
    - name: fabric
      persistentVolumeClaim:
        claimName: fabric-pvc
    - name: run
      hostPath:
        path: /var/run 