apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: hyperledger
    peer-id: {{ .Values.peerName }}  

spec:
  containers:
  - name: couchdb
    image: hyperledger/fabric-couchdb    
    ports:
      - containerPort: 5984

  - name: {{ .Values.peerName }}
    image: hyperledger/fabric-peer:{{ .Chart.AppVersion }}
    env:
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric/config
    - name: CORE_VM_ENDPOINT
      value: "unix:///host/var/run/docker.sock"
    - name: CORE_PEER_ID
      value: {{ .Values.peerName }}
    - name: FABRIC_LOGGING_SPEC
      value: {{ .Values.FABRIC_LOGGING_SPEC }}
    - name: CORE_CHAINCODE_LOGGING_LEVEL
      value: {{ .Values.CORE_CHAINCODE_LOGGING_LEVEL }}
    - name: CORE_PEER_LOCALMSPID
      value: {{ .Values.MSPName }}
    - name: CORE_PEER_MSPCONFIGPATH
      value: /etc/hyperledger/fabric/crypto/msp
    - name: CORE_PEER_ADDRESS
      value: {{ .Values.CORE_PEER_ADDRESS }}
    - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
      value: {{ .Values.CORE_PEER_GOSSIP_EXTERNALENDPOINT }}
    - name: CORE_PEER_GOSSIP_BOOTSTRAP
      value: {{ .Values.CORE_PEER_GOSSIP_BOOTSTRAP }}
    - name: CORE_PEER_ADDRESSAUTODETECT
      value: "true"
    - name: CORE_LEDGER_STATE_STATEDATABASE
      value: CouchDB
    - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
      value: "localhost:5984"
    - name: CORE_VM_DOCKER_ATTACHSTDOUT
      value: "true"
    workingDir: /etc/hyperledger/fabric
    ports:
      - containerPort: 7051
      - containerPort: 7052
      - containerPort: 7053
    command: ["peer"]
    args: ["node","start","--peer-chaincodedev"]
    volumeMounts:
    - name: fabric
      subPath: config/{{ .Values.peerName }}
      mountPath: /etc/hyperledger/fabric/config
    - name: fabric
      subPath: {{ .Values.orgMSPPath }}
      mountPath: /etc/hyperledger/fabric/crypto
    - name: fabric
      subPath: blocks
      mountPath: /etc/hyperledger/fabric/blocks
    - name: fabric
      subPath: data/{{ .Values.peerName }}
      mountPath: /var/hyperledger/production
    - name: run
      mountPath: /host/var/run/
  volumes:
    - name: fabric
      persistentVolumeClaim:
        claimName: fabric-pvc
    - name: run
      hostPath:
        path: /var/run