apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: hyperledger
    peer-id: {{ .Values.peerName }}  

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}  
    spec:
      serviceAccountName: fabric
      # initContainers:
      #   - name: create-channel-block
      #     image: hyperledger/fabric-tools:1.4.4
      #     command: ["configtxgen"]
      #     args: ["-profile","DevSingleMSPChannel","-configPath","/etc/hyperledger/fabric/config","-outputCreateChannelTx","/etc/hyperledger/fabric/block/general-channel.tx","-channelID","general"]
      #     env:
      #       - name: FABRIC_CFG_PATH
      #         value: /etc/hyperledger/fabric/config
      #       - name: CORE_PEER_LOCALMSPID
      #         value: {{ .Values.MSPName }}
      #       - name: CORE_PEER_MSPCONFIGPATH
      #         value: /etc/hyperledger/fabric/msp
      #       - name: CORE_PEER_ADDRESS
      #         value: {{ .Values.CORE_PEER_ADDRESS }} 
      #       - name: FABRIC_LOGGING_SPEC
      #         value: INFO                             
      #     volumeMounts:
      #       - name: block
      #         mountPath: /etc/hyperledger/fabric/block        
      #       - name: localmsp-org
      #         mountPath: /etc/hyperledger/fabric/msp                
      #       - name: config
      #         mountPath: /etc/hyperledger/fabric/config
      #   - name: create-anchor-block
      #     image: hyperledger/fabric-tools:1.4.4
      #     command: ["configtxgen"]
      #     args: ["-profile","DevSingleMSPChannel","-configPath","/etc/hyperledger/fabric/config","-outputAnchorPeersUpdate","/etc/hyperledger/fabric/block/PeerMSPanchors.tx","-channelID","general","-asOrg","PeerMSP"]
      #     env:
      #       - name: FABRIC_CFG_PATH
      #         value: /etc/hyperledger/fabric/config
      #       - name: CORE_PEER_LOCALMSPID
      #         value: {{ .Values.MSPName }}
      #       - name: CORE_PEER_MSPCONFIGPATH
      #         value: /etc/hyperledger/fabric/msp
      #       - name: CORE_PEER_ADDRESS
      #         value: {{ .Values.CORE_PEER_ADDRESS }} 
      #       - name: FABRIC_LOGGING_SPEC
      #         value: INFO                             
      #     volumeMounts:
      #       - name: block
      #         mountPath: /etc/hyperledger/fabric/block        
      #       - name: localmsp-org
      #         mountPath: /etc/hyperledger/fabric/msp                
      #       - name: config
      #         mountPath: /etc/hyperledger/fabric/config
      #   - name: create-peer-channel
      #     image: hyperledger/fabric-tools:1.4.4
      #     command: ["peer"]
      #     args: ["channel","create","-o","orderer:7050","-c","general","-f","/etc/hyperledger/fabric/block/general-channel.tx","--outputBlock","/etc/hyperledger/fabric/block/general.block"]
      #     env:
      #       - name: FABRIC_CFG_PATH
      #         value: /etc/hyperledger/fabric/config
      #       - name: CORE_PEER_LOCALMSPID
      #         value: {{ .Values.MSPName }}
      #       - name: CORE_PEER_MSPCONFIGPATH
      #         value: /etc/hyperledger/fabric/msp
      #       - name: CORE_PEER_ADDRESS
      #         value: {{ .Values.CORE_PEER_ADDRESS }} 
      #       - name: FABRIC_LOGGING_SPEC
      #         value: INFO                             
      #     volumeMounts:
      #       - name: block
      #         mountPath: /etc/hyperledger/fabric/block         
      #       - name: localmsp-peeradmin
      #         mountPath: /etc/hyperledger/fabric/msp                
      #       - name: config
      #         mountPath: /etc/hyperledger/fabric/config
        # - name: join-peer-channel
        #   image: hyperledger/fabric-tools:1.4.4
        #   command: ["peer"]
        #   args: ["channel","join","-o","orderer:7050","-b","/etc/hyperledger/fabric/block/general.block"]
        #   env:
        #     - name: FABRIC_CFG_PATH
        #       value: /etc/hyperledger/fabric/config
        #     - name: CORE_PEER_LOCALMSPID
        #       value: {{ .Values.MSPName }}
        #     - name: CORE_PEER_MSPCONFIGPATH
        #       value: /etc/hyperledger/fabric/msp
        #     - name: CORE_PEER_ADDRESS
        #       value: {{ .Values.CORE_PEER_ADDRESS }} 
        #     - name: FABRIC_LOGGING_SPEC
        #       value: INFO                             
        #   volumeMounts:
        #     - name: block
        #       mountPath: /etc/hyperledger/fabric/block         
        #     - name: localmsp-peeradmin
        #       mountPath: /etc/hyperledger/fabric/msp                
        #     - name: config
        #       mountPath: /etc/hyperledger/fabric/config
  
      containers:
        - name: couchdb
          image: hyperledger/fabric-couchdb    
          ports:
            - containerPort: 5984

        - name: {{ .Values.peerName }}
          image: hyperledger/fabric-peer:{{ .Chart.AppVersion }}
          env:
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/config
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/msp
            - name: CORE_PEER_ID
              value: {{ .Values.peerName }}
            - name: FABRIC_LOGGING_SPEC
              value: {{ .Values.FABRIC_LOGGING_SPEC }}
            - name: CORE_CHAINCODE_LOGGING_LEVEL
              value: {{ .Values.CORE_CHAINCODE_LOGGING_LEVEL }}
            - name: CORE_PEER_LOCALMSPID
              value: {{ .Values.MSPName }}
            - name: CORE_PEER_ADDRESS
              value: {{ .Values.CORE_PEER_ADDRESS }}
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: {{ .Values.CORE_PEER_GOSSIP_EXTERNALENDPOINT }}
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: {{ .Values.CORE_PEER_GOSSIP_BOOTSTRAP }}
            - name: CORE_VM_DOCKER_ATTACHSTDOUT
              value: "true"
            - name: CORE_PEER_FILESYSTEMPATH
              value: /etc/hyperledger/fabric/ledger
          workingDir: /etc/hyperledger/fabric
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          command: ["peer"]
          args: ["node","start","--peer-chaincodedev"]
          volumeMounts:
            - name: block
              mountPath: /etc/hyperledger/fabric/block
            - name: ledger
              mountPath: /etc/hyperledger/fabric/ledger
            - name: localmsp
              mountPath: /etc/hyperledger/fabric/msp
            - name: config
              mountPath: /etc/hyperledger/fabric/config
            - name: run
              mountPath: /host/var/run/
      volumes:
        - name: block
          hostPath:
            path: /data/{{ .Values.peerName }}/block
        - name: ledger
          hostPath:
            path: /data/{{ .Values.peerName }}/ledger 
        - name: localmsp
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: ca-cert.pem
                path: cacerts/ca.dev.angus.net-cert.pem
              - key: PeerMSP-cert.pem
                path: signcerts/peer0.dev.angus.net-cert.pem
              - key: PeerMSP-key.pem
                path: keystore/PeerMSP-key.pem
              - key: PeerAdmin-cert.pem
                path: admincerts/Admin
        - name: localmsp-org
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: ca-cert.pem
                path: cacerts/ca.dev.angus.net-cert.pem
              - key: PeerAdmin-cert.pem
                path: admincerts/Admin
        - name: localmsp-peeradmin
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: ca-cert.pem
                path: cacerts/ca.dev.angus.net-cert.pem
              - key: PeerAdmin-cert.pem
                path: admincerts/Admin
              - key: PeerAdmin-cert.pem
                path: signcerts/Admin
              - key: PeerAdmin-key.pem
                path: keystore/Admin                
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: configtx.yaml
                path: configtx.yaml
              - key: core.yaml
                path: core.yaml

        - name: run
          hostPath:
            path: /var/run