---
name: fabric-network
version: 1.0.0
caName: ca.angus.net
mspName: PeerMSP
client:
    organization: Dev
    connection:
        timeout:
            peer:
                endorser: '300'
            orderer: '300'
channels:
    general:
        orderers:
        - orderer.angus.net
        peers:
            peer0.dev.angus.net: {}
organizations:
    Dev:
        mspid: PeerMSP
        peers:
        - peer0.dev.angus.net
        certificateAuthorities:
        - ca.angus.net
orderers:
    orderer.angus.net:
        url: grpc://orderer:7050
peers:
    peer0.dev.angus.net:
        url: grpc://peer0:7051
certificateAuthorities:
    ca.angus.net:
        url: http://ca:7054
        caName: ca.angus.net
